# Generated by Django 3.2 on 2022-03-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='customer',
            new_name='user',
        ),
    ]
