# Generated by Django 3.2 on 2022-03-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220312_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='update',
            name='user',
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.investor'),
        ),
        migrations.AddField(
            model_name='update',
            name='investor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='investment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
